### ISSUE TITLE
Would running a series of BizLogic with a transaction be useful?

### ISSUE THREAD

**Issue by JonPSmith** [JonPSmith/EfCore.GenericBizRunner#1]
In my previous version of the GenericBizRunner I had a feature that would run a series of business logic methods inside a transaction, e.g.

**Start database transaction**
* Run business logic 1
* Run business logic 2
* Run business logic 3
* Commit if all OK, or rollback if any failed  

**End transaction**

*See [this article](http://www.thereformedprogrammer.net/architecture-of-business-layer-calling-multiple-business-methods-in-one-http-request/) for a detailed description of this feature*.

I don't know if people would find this feature useful. If you would like it then add a  👍 or 👎 to this issue.

**Comment by nj-sketch** [comment]
👍

**Comment by ramhemasri** [comment]
👍

**Comment by leogcba** [comment]
👍

**Comment by JonPSmith** [comment]
Thanks for voting. I do plan to implement the transaction idea, but having looked at the [planned change to to support System.Transactions](https://github.com/aspnet/EntityFrameworkCore/issues/5595) in EF Core 2.1.0 I'm going to wait.

I think the change in 2.1.0 will make handling multiple DbContexts, known as *bounded contexts* in DDD, easier to implement within a transaction.

**Comment by rbasniak** [comment]
👍

**Comment by zhudashao** [comment]
Hi @JonPSmith , after reading your book ef in action, i apprieciate that you share your experience and the code. i have used your conception (GenericBizRunner)in my project. recently i have another project, 
i use directly your EfCore.GenericBizRunner component.
and now i have a problem for using transaction with GenericBizRunner for save data in some tables at the same time, i have read your article here
https://www.thereformedprogrammer.net/architecture-of-business-layer-calling-multiple-business-methods-in-one-http-request/ 
but i can't figure out how to write my code in bizLogic or in an action class.
can you give me some suggestion ?
thanks.

ZHU

**Comment by JonPSmith** [comment]
Hi @zhudashao,

I'm sorry to say I didn't add transactions to the GenericBizRunner. Its not trivial to add multi-business logic with transactions and I just didn't feel the effort was worth it. On top of that, what will you do if the transaction is retried - see section 9.7 "Handling database connection problems" where business logic can be called multiple times.

Personally, if I have something that needs transactions then I write it by hand, as its obviously complex. 

You can always use the super-simple `RunnerTransact2WriteDb<TIn, TPass, TOut>` I describe in my book - section 4.6.2. Also, the code for that can be found in the EfCoreInAction repo - chapter04

**Comment by zhudashao** [comment]
@JonPSmith thank you for your response and suggestion. I take inspiration from your RunnerTransact2WriteDb to add more actions to the transaction. finally I was able to separate the logic of this operation. your book really helped me a lot
thanks
