### ISSUE TITLE
Database migrations

### ISSUE THREAD

**Issue by szilardd** [JonPSmith/EfCore.GenericBizRunner#11]
How do you go about making changes to the database structure (without recreating the whole database)? For example adding a new field to `Order` entity/table. Is it possible to generate migrations? 

I use the `ExampleWebApp` webapp provided in the repo.

Added a new property called `ISBN` to `Order` entity and tried to generate a migration like this:

`add-migration Added_ISBN_To_Order -Context OrderDbContext`

but got error

`Unable to create an object of type 'OrderDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<OrderDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.`

I'm especially interested in how this works when there are multiple db contexts (https://github.com/JonPSmith/EfCore.GenericBizRunner/wiki/Using-multiple-DbContexts)

Thanks

**Comment by JonPSmith** [comment]
Hi @szilardd,

This is a migration issue and the GenericBizRunner example application isn't set up for migrations. I just needed a database to demo and I used an Sqlite in-memory database - that can't be migrated.

You should look at the EF Core [Migration docs](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/) which covers migrations in detail.

On you point about multiple db contexts, that is useful in some situations but it makes migrations complex. I am updating my book [Entity Framework Core in Action](https://bit.ly/EfCoreBook2) and I will be covering how to do this and building an application using multiple db contexts - but that won't be ready for many months.
