### ISSUE TITLE
Dead link to UnitTest example in Wiki

### ISSUE THREAD

**Issue by chrisbbe** [JonPSmith/EfCore.GenericBizRunner#12]
Hi,

Wiki page [Unit and integration testing](https://github.com/JonPSmith/EfCore.GenericBizRunner/wiki/Unit-and-integration-testing) has a dead link; "Have a look at this [unit test](https://github.com/JonPSmith/EfCore.GenericBizRunner/blob/4a71aeedaeb12ec708a13eb85425b1d36a0478b2/TestNetStandard2_0Only/UnitTests/ExampleBizLogic/TestBizLogic.cs) as an example." on the top of the page, I assume it should point to this [example](https://github.com/JonPSmith/EfCore.GenericBizRunner/blob/4a71aeedaeb12ec708a13eb85425b1d36a0478b2/TestNetStandard2_0Only/UnitTests/ExampleBizLogic/TestBizLogic.cs).

_It is a pity one cannot make PR for Wiki pages in GitHub, I would rather provide a PR than raising an issue._

Cheers

**Comment by JonPSmith** [comment]
Thanks @chrisbbe - I have updated that link.
