### ISSUE TITLE
Returning the actualt result instead of default(TOut)

### ISSUE THREAD

**Issue by chrisbbe** [JonPSmith/EfCore.GenericBizRunner#13]
Hi,

Thanks for sharing and maintaining this library. I find this library explicitly useful to encapsulate by business logic. On the other side, if find the mechanism of converting the output of the business logic into a useful HTTP response a bit weak. Currently, I'm thinking about in some cases to bypass the feature of the EfCore.GenericService.AspNetCore library to construct my responses, and instead, do it "manually" in the controller. 

As this library encapsulates the Business Logic, I want my business logic (_Action class_) to report the corresponding HttpStatus code beside any textual errors reported by the `AddError(string errorMessage, ...)` method. At first, in my mind, without any changes in any of the libraries, I thought of returning a Tuple from the Action class where one element would represent the HttpStatusCode to be returned by the controller. But sadly I discovered that the ActionService returns `default(TOut)` instead of the actual result of the business logic is executed when the `bizInstance` has errors.

https://github.com/JonPSmith/EfCore.GenericBizRunner/blob/1c5adf67554a055a66558ce5349bbbdbb76a81ea/GenericBizRunner/Internal/Runners/ActionServiceInOut.cs#L33

What will be the arguments and side effects of changing the library to actually return the result of the BizAction, instead of `default(TOut)` ? Something like this:
```
//This handles optional call of save changes
SaveChangedIfRequiredAndNoErrors(db, bizStatus);
// if (bizStatus.HasErrors) return default(TOut);

return fromBizCopier.DoCopyFromBiz<TOut>(db, WrappedConfig.FromBizIMapper, result);
```

**Comment by JonPSmith** [comment]
I see what you want to do and yes, you could comment out the `if (bizStatus.HasErrors) return default(TOut);` in the `...InOut` and `...Out` versions of the services. 

It might also be easier to always use what is known as `DirectCopy` where the `TOut` from `...InOut` etc. matches the `RunBizAction<TOut>(object inputData);` call. This just passes the data without it going though AutoMapper.

**Comment by chrisbbe** [comment]
Thanks for the quick feedback. 

Wouldn't `DirectCopy` be performed anyway in cases where the type of `TBizOut `and `TOut` is equal?

Is this change wanted in the library?

**Comment by JonPSmith** [comment]
> Wouldn't DirectCopy be performed anyway in cases where the type of TBizOut and TOut is equal?

Yes, I was just suggesting you use that (but AutoMapper should work).

> Is this change wanted in the library?

No. I assume you will clone the repo and create your own version.

**Comment by chrisbbe** [comment]
> No. I assume you will clone the repo and create your own version.

Really, isn't open-source about forming a community, where we together discuss and make changes to make the software better and usable for a larger audience? My proposal is not a breaking change, nor a significant change out of the scope of the library. **I'm happy to provide a pull-request if your open to consider merging the PR in the end.**

**Comment by JonPSmith** [comment]
Actually that IS a significant breaking change and my EfCore.GenericServices also has this feature.  My code relies on this in some places, but the main thing is if the user doesn't check the status for errors, then the default value, often a null, might cause an exception. 

You should know I'm very busy but I spent about 1/2 hour trying to come up of ways you could do that without a change to the library but I couldn't come up with anything. Sorry, but that's the situation.
