### ISSUE TITLE
Project-based business logic

### ISSUE THREAD

**Issue by Anapher** [JonPSmith/EfCore.GenericBizRunner#3]
Hey,
no idea if you can help me with that, but I'm having huge problems adapting this library for my project:
In my application, users can create their own projects and create notes for these projects (as an example). The problem is now that beside the DTO for the note, the business logic needs to know the project id in order to create the note. Actually, the best would be to accept the project id as a second input, but that is not possible with this library. My solution was to use a generic wrapper class `ProjectContext<T>`, and every DTO must be wrapped using it, but this solution is rather ugly, also because this library is not strongly typed.

I have around 30 business logic classes that require the project id in order to execute their action, I thought about creating something like this:
```cs
    public interface IProjectActionAsync<in TIn, TOut> : IBizActionStatus
    {
        Guid ProjectId { get; set; }
        Task<TOut> BizActionAsync(TIn inputData);
    }

    public interface IProjectActionServiceAsync<TContext, TBizInstance>
        where TContext : DbContext where TBizInstance : class
    {
        Task<TOut> RunBizActionAsync<TOut>(object inputData, Guid projectId);
        Task<TOut> RunBizActionAsync<TOut>(Guid projectId);
        Task RunBizActionAsync(object inputData, Guid projectId);
        //...
    }
```
but I'd have to rewrite your whole library (and project independent business logic wouldn't be possible anymore).
I really liked your book and I'm sure you created something huge here, but I'm still not sure if it fits my needs. How would you handle that?

**Comment by JonPSmith** [comment]
Hi @Anapher,

OK, here is what I understand form your issue:  
You have a series of business logic that takes in some per-business logic data (what you call a DTO), but all of them need the `ProjectId`. I'm assuming you are happy to make each piece of business logic into a separate class, so its about the best way to input the per-business data and the `ProjectId`.

Assuming I'm understanding your issue my first idea is to have all of your per-business logic DTOs which inherit from a class that contains the `ProjectId`. If your not using the `GenericActionToBizDto<,>` or `GenericActionToBizDtoAsync<,>` class with mapping then its easy. e.g.

```c#
public class ProjectIdClass
{
   public Guid ProjectId { get; set; }
}

public class BizLogicDto1 : ProjectIdClass
{
   //... the per-business data for biz logic 1
}

public class BizLogicDto2 : ProjectIdClass
{
   //... the per-business data for biz logic 2
}
... etc.
```

If you do want to use the `GenericActionToBizDto<,>` etc. then I think you will need your own version of that DTO, but with your `ProjectId` in it. That's possible, but I little more difficult, but I can walk you through that if needed.

The other option if that just doesn't work for you is to use the simple BizRunner code I write for chapter 4 (found in Chapter04 branch of EfCoreInAction). You could adapt the simple BizRunner code to exactly what you want. The BizRunner in chapter 4 isn't as flexible as this library, but maybe you don't need the extra features in `GenericBizRunner`.

**Comment by Anapher** [comment]
Hey,
thank you for your answer.

> the simple BizRunner code I write for chapter 4

Yeah, that's what I was using before, think I will stick to that and try to improve it a little bit so it looks like this library. Cheers, and thank you again for writing that book, you really got me into that stuff :)

**Comment by JonPSmith** [comment]
Good call. Glad the chapter has helped with your business logic - It took many years to get a good pattern. All the best with your project.
