### ISSUE TITLE
ActionService mapping to TOut2

### ISSUE THREAD

**Issue by piotrkolodziej** [JonPSmith/EfCore.GenericBizRunner#6]
Hello,

I want to achieve two things in my WebAPI project:

1. I want my actions to return data-level entities so that after calling save changes the Primary Keys will be updated (so that they are there before mapping is called)
2. I want my ActionService to map data-level entity (TOut) to another level model (narrowing down the set of properties when needed).

Is that possible? Either I am missing something or the project only allowes to narrow down the input data before passing it to actions and does not care much about narrowing down the result set––for the WebAPI with Angular I think the latter is more important.

I would appreciate the feedback
Best
Piotr

**Comment by JonPSmith** [comment]
Hi @piotrkolodziej,

GenericBizRunner is designed to map the input and the output to another class BUT I made my DTO's inherit AutoMapper's Profile class. I thought that would make it easier for users, but I found that AutoMapper's Profile class has a load of public properties, which means if you map the entity to my `GenericActionFromBizDto` class you get the Profile's properties too. That means it doesn't work for Web API projects.

I'm working on a WebApi/Angular system for a client. At the moment we got around this problem by only using GenericBizRunner to create an entity, and we use the "return url to get created entity" approach. We MAY need to fix this for this project, but at the moment we don't have a burning need so I'm not going to do it now (it's quite a bit of work, but I know what to do as fixed the problem in my [EfCore.GenericServices](https://github.com/JonPSmith/EfCore.GenericServices). But that library is about CRUD, not business logic so don't think it will be useful).  

So, I will fix it sometime, but its likely to be months away. I will leave this issue open.

**Comment by JonPSmith** [comment]
Version 3 has fixed the problem with extra properties appearing in DTOs. This means you can use GenericBizRunner with Web APIs.

See [EfCore.GenericServices.AspNetCore](https://github.com/JonPSmith) support library and the article called [How to write good, testable ASP.NET Core Web API code quickly](https://www.thereformedprogrammer.net/how-to-write-good-testable-asp-net-core-web-api-code-quickly/) for how to use GeneriBizRunner with ASP.NET Core's Web API.
