### ISSUE TITLE
Test exception

### ISSUE THREAD

**Issue by Allann** [JonPSmith/EfCore.GenericBizRunner#7]
I downloaded the latest version of your code and ran the tests manually, and they all passed.  I was going to have a play with some of the code so turned on Live Tests and this failed:

Test Name:	Tests.UnitTests.DDDEntities.TestDddBookLoad.TestLoadBooksOk
Test FullName:	Tests.UnitTests.DDDEntities.TestDddBookLoad.TestLoadBooksOk
Test Source:	f:\Repos\EfCore.GenericBizRunner\Tests\UnitTests\DDDEntities\TestDddBookLoad.cs : line 16
Test Outcome:	Failed
Test Duration:	0:00:00.01

Result StackTrace:	
at TestSupport.Helpers.TestData.GetCallingAssemblyTopLevelDir(Assembly callingAssembly)
   at Tests.UnitTests.DDDEntities.TestDddBookLoad.TestLoadBooksOk()
Result Message:	System.Exception : Did not find '\bin\' in the assembly. Do you need to provide the callingAssembly parameter?

Running on VS2019 Preview 3.

**Comment by JonPSmith** [comment]
Hi @Allann,

I haven't tried live tests (I don't have that feature in my VS). My code relies on finding the folder of the running assembly to work out where it is (I need that for the appsetting.json directory). It looks like live test breaks this, hence I throw an exception. 

Not sure how to get around that. If you know of a reliable way to find the path to the assembly/project I would be interested to know.

**Comment by baoduy** [comment]
This is common issue when using live test for those unit tests that looking for the file in local folder as live test base directory is not point to local bin folder.
