### ISSUE TITLE
Abstracted, dynamic, IActionService.RunBizAction() makes code analysis problematic

### ISSUE THREAD

**Issue by douglasg14b** [JonPSmith/EfCore.GenericBizRunner#8]
When reading through your project I'm noticing that It's difficult to automatically find and identify method usage and to map call trees, as many of the trees (Going up, starting from Controller methods) meet dead ends in calls to dynamic objects. This is partially overcomeable by understanding your library and knowing that you must follow the generic for `IActionService`, but still completely breaks automatic code analysis right from the get-go.

I'm interested in your project, but the crux of the matter is that this is concerning, and seems like an operational efficiency risk... Without the ability to use the tools provided for .Net code analysis, how can a codebase be effectively mapped, or future developers quickly jump in and understand the call hierarchy? 

It's almost feels like a form of crude obfuscation.

This seems like a flaw with this library. What are your thoughts on this?

**Comment by JonPSmith** [comment]
Hi @douglasg14b,

The use of dynamic types and dynamic creation of classes is required to make the *Generic* part of GenericBizRunner work. There is no way around that. I describe how I use Generic in an (old) article [Using .NET Generics with a type derived at runtime](https://www.thereformedprogrammer.net/using-net-generics-with-a-type-derived-at-runtime/).

If you want a simpler approach then I have a basic BizRunner in my book [Entity Framework Core in Action](http://bit.ly/2m8KRAZ), which I describe in chapter 4, and the code is in the [Chapter04 branch](https://github.com/JonPSmith/EfCoreInAction/tree/Chapter04) of the companion EfCoreInAction GitHub repo.
